import { checkCardQuality } from "@/lib/flashcard/quality-gate";
import {
  countDueFlashcards,
  findChapterByIdOrNo,
  findDeckByName,
  findFlashcardById,
  getFlashcardStatsSnapshot,
  getLatestReviewHistory,
  getLatestReviewRecord,
  insertDeck,
  insertFlashcard,
  insertReview,
  insertReviewHistory,
  jsonField,
  listFlashcards,
  listRecentFlashcardReviews,
  markReviewHistoryUndone,
  refreshLeechFlags,
  updateFlashcardById,
  burySiblingCards,
  deleteReviewRecord,
} from "@/lib/flashcards/queries";
import { fsrsCardToDBFields, stateFromString, stateToString } from "@/lib/srs/card-converter";
import type { Card } from "@/lib/srs/fsrs-engine";
import { createFsrsEngine, type FsrsGrade } from "@/lib/srs/fsrs-engine";

type FlashcardType = "basic" | "basic_reverse" | "cloze" | "image_occlusion" | "mcq";
type FlashcardSourceType = "manual" | "question" | "note";
type FlashcardStatus = "active" | "pending_review";

export interface CreateFlashcardInput {
  front: string;
  back: string;
  type?: FlashcardType;
  chapterId?: string | null;
  chapterNo?: number | null;
  sourceQuestionId?: string | null;
  sourceDocId?: string | null;
  sourceFrameId?: string | null;
  anchorId?: string | null;
  highlightText?: string | null;
  educationalObjective?: string | null;
  tags?: string[] | null;
  deck?: string | null;
  sourceType?: FlashcardSourceType;
  importance?: number | null;
  status?: FlashcardStatus;
}

export interface ManagedFlashcardCard {
  id: string;
  frontHtml: string;
  backHtml: string;
  cardType: string;
  chapterNo: number | null;
  chapterTitle: string | null;
  sourceQuestionId: string | null;
  sourceDocId: string | null;
  sourceFrameId: string | null;
  tags: string[];
  deck: string | null;
  dueAt: number | null;
  state: string;
  intervalDays: number;
  isLeech: boolean;
  isSuspended: boolean;
  /** Real FSRS retrievability probability (0–1). Null for new/unreviewed cards. */
  retrievability: number | null;
  predictions: {
    again: { interval: string; days: number };
    hard: { interval: string; days: number };
    good: { interval: string; days: number };
    easy: { interval: string; days: number };
  };
}

function makeId(prefix: string) {
  return `${prefix}_${crypto.randomUUID()}`;
}

function resolveDeckName(input: {
  explicitDeck?: string | null;
  sourceType?: FlashcardSourceType;
  chapterNo?: number | null;
  chapterTitle?: string | null;
}) {
  if (input.explicitDeck?.trim()) {
    return input.explicitDeck.trim();
  }

  if (input.chapterNo && input.chapterTitle) {
    return `Chapter ${input.chapterNo}: ${input.chapterTitle}`;
  }

  if (input.sourceType === "question") {
    return "From Questions";
  }

  if (input.sourceType === "note") {
    return "From Notes";
  }

  return "General";
}

function modeFromExamDate(examDate?: number | null) {
  if (!examDate) return "medical" as const;
  const daysUntilExam = Math.floor((examDate - Date.now()) / (24 * 60 * 60 * 1000));
  return daysUntilExam <= 60 ? ("exam_crunch" as const) : ("medical" as const);
}

async function ensureDeckRecord(name: string, chapterNo?: number | null) {
  const existing = await findDeckByName(name, chapterNo ?? null);
  if (existing) return existing;

  const now = Date.now();
  return insertDeck({
    id: makeId("deck"),
    name,
    chapterNo: chapterNo ?? null,
    isAutoGenerated: chapterNo ? 1 : 0,
    createdAt: now,
    updatedAt: now,
  });
}

function toManagedReviewCard(card: Awaited<ReturnType<typeof listFlashcards>>[number]) {
  const engine = createFsrsEngine("medical");
  const now = new Date();
  const reviewCard: Card = {
    due: new Date(card.fsrsDue ?? Date.now()),
    stability: card.fsrsStability,
    difficulty: card.fsrsDifficulty,
    elapsed_days: card.fsrsElapsedDays,
    scheduled_days: card.fsrsScheduledDays,
    learning_steps: card.learningStep,
    reps: card.fsrsReps,
    lapses: card.fsrsLapses,
    state: stateFromString(card.fsrsState),
    last_review: card.fsrsLastReview ? new Date(card.fsrsLastReview) : undefined,
  };
  const predictions = engine.getPredictions(reviewCard, now);

  // Compute real FSRS retrievability. New/unreviewed cards (reps===0 or state==="new")
  // have no decay history, so we expose null rather than the misleading value of 1.
  let retrievability: number | null = null;
  if (card.fsrsState !== "new" && card.fsrsReps > 0) {
    try {
      const r = engine.getRetrievability(reviewCard, now);
      retrievability = Number.isFinite(r) && r >= 0 && r <= 1 ? r : null;
    } catch {
      retrievability = null;
    }
  }

  return {
    id: card.id,
    frontHtml: card.frontHtml,
    backHtml: card.backHtml,
    cardType: card.cardType,
    chapterNo: card.chapterNo,
    chapterTitle: card.chapterTitle,
    sourceQuestionId: card.sourceQuestionId,
    sourceDocId: card.sourceDocId,
    sourceFrameId: card.sourceFrameId,
    tags: card.tags,
    deck: card.deck,
    dueAt: card.fsrsDue,
    state: card.fsrsState,
    intervalDays: card.fsrsScheduledDays,
    isLeech: card.isLeech,
    isSuspended: card.isSuspended,
    retrievability,
    predictions,
  };
}

export async function createManagedFlashcard(input: CreateFlashcardInput) {
  const chapter = await findChapterByIdOrNo({
    chapterId: input.chapterId ?? null,
    chapterNo: input.chapterNo ?? null,
  });
  const deckName = resolveDeckName({
    explicitDeck: input.deck,
    sourceType: input.sourceType,
    chapterNo: chapter?.chapterNo ?? input.chapterNo ?? null,
    chapterTitle: chapter?.title ?? null,
  });
  const deckRecord = await ensureDeckRecord(deckName, chapter?.chapterNo ?? input.chapterNo ?? null);

  const quality = checkCardQuality({
    front: input.front,
    back: input.back,
    source:
      input.sourceType === "question"
        ? "question"
        : input.type === "cloze"
          ? "cloze"
          : input.sourceType === "note"
            ? "highlight"
            : "qa",
    importance: input.importance ?? undefined,
  });

  const now = Date.now();
  const engine = createFsrsEngine("medical");
  const emptyCard = engine.createCard(new Date(now));

  const record = await insertFlashcard({
    id: makeId("fc"),
    chapterId: input.chapterId ?? chapter?.id ?? null,
    chapterNo: input.chapterNo ?? chapter?.chapterNo ?? null,
    sourceQuestionId: input.sourceQuestionId ?? null,
    sourceDocId: input.sourceDocId ?? null,
    sourceFrameId: input.sourceFrameId ?? null,
    anchorId: input.anchorId ?? null,
    highlightText: input.highlightText ?? null,
    cardType: input.type ?? "basic",
    createdFrom: input.sourceType ?? "manual",
    status: input.status ?? (quality.score >= 70 ? "active" : "pending_review"),
    deck: deckName,
    deckId: deckRecord?.id ?? null,
    frontHtml: input.front,
    backHtml: input.back,
    educationalObjective: input.educationalObjective ?? null,
    tagsJson: jsonField(input.tags ?? null),
    sourceJson: jsonField(
      input.sourceDocId || input.sourceQuestionId
        ? {
            sourceType: input.sourceType ?? "manual",
            sourceDocId: input.sourceDocId ?? null,
            sourceQuestionId: input.sourceQuestionId ?? null,
            sourceFrameId: input.sourceFrameId ?? null,
          }
        : null,
    ),
    importance: input.importance ?? 5,
    ...fsrsCardToDBFields(emptyCard),
    fsrsDue: emptyCard.due.getTime(),
    createdAt: now,
    updatedAt: now,
  });

  if (!record) {
    throw new Error("Failed to create flashcard");
  }

  return {
    record,
    quality,
  };
}

export async function listManagedFlashcards(input: { search?: string; limit?: number } = {}) {
  return listFlashcards({
    search: input.search,
    limit: input.limit ?? 48,
  });
}

export async function listManagedDueFlashcards(limit = 100, chapterNo?: number) {
  const cards = await listFlashcards({
    dueOnly: true,
    limit,
    chapterNo,
  });

  return cards.map(toManagedReviewCard);
}

export async function getManagedFlashcardStats() {
  const [stats, recentActivity] = await Promise.all([
    getFlashcardStatsSnapshot(),
    listRecentFlashcardReviews(),
  ]);

  return {
    ...stats,
    recentActivity,
  };
}

export async function reviewManagedFlashcard(input: {
  flashcardId: string;
  rating: FsrsGrade;
  sessionId?: string | null;
  timeSpentMs?: number | null;
  examDate?: number | null;
}) {
  const flashcard = await findFlashcardById(input.flashcardId);
  if (!flashcard) {
    throw new Error("Flashcard not found");
  }

  const engine = createFsrsEngine(modeFromExamDate(input.examDate));
  const current: Card = {
    due: new Date(flashcard.fsrsDue ?? Date.now()),
    stability: flashcard.fsrsStability,
    difficulty: flashcard.fsrsDifficulty,
    elapsed_days: flashcard.fsrsElapsedDays,
    scheduled_days: flashcard.fsrsScheduledDays,
    learning_steps: flashcard.learningStep,
    reps: flashcard.fsrsReps,
    lapses: flashcard.fsrsLapses,
    state: stateFromString(flashcard.fsrsState),
    last_review: flashcard.fsrsLastReview ? new Date(flashcard.fsrsLastReview) : undefined,
  };
  const now = new Date();
  const result = engine.review(current, input.rating, now);
  const nextFields = fsrsCardToDBFields(result.card);

  const updated = await updateFlashcardById(flashcard.id, {
    ...nextFields,
  });

  if (!updated) {
    throw new Error("Failed to update flashcard");
  }

  await insertReview({
    id: makeId("fcr"),
    flashcardId: flashcard.id,
    rating: input.rating,
    state: stateToString(result.card.state),
    dueAt: result.card.due.getTime(),
    reviewedAt: now.getTime(),
    elapsedDays: result.card.elapsed_days,
    scheduledDays: result.card.scheduled_days,
    stability: Math.round(result.card.stability * 1000),
    difficulty: Math.round(result.card.difficulty * 1000),
    retrievability: Math.round(engine.getRetrievability(result.card, now) * 1000),
    fsrsSnapshotJson: jsonField({
      mode: engine.getMode(),
      due: result.card.due.toISOString(),
      scheduledDays: result.card.scheduled_days,
    }),
  });

  await insertReviewHistory({
    id: makeId("fch"),
    flashcardId: flashcard.id,
    sessionId: input.sessionId ?? null,
    rating: input.rating,
    previousState: JSON.stringify({
      fsrsDue: flashcard.fsrsDue,
      fsrsState: flashcard.fsrsState,
      fsrsStability: flashcard.fsrsStability,
      fsrsDifficulty: flashcard.fsrsDifficulty,
      fsrsElapsedDays: flashcard.fsrsElapsedDays,
      fsrsScheduledDays: flashcard.fsrsScheduledDays,
      fsrsReps: flashcard.fsrsReps,
      fsrsLapses: flashcard.fsrsLapses,
      fsrsLastReview: flashcard.fsrsLastReview,
      learningStep: flashcard.learningStep,
      intervalDays: flashcard.intervalDays,
      easeFactor: flashcard.easeFactor,
    }),
    newState: JSON.stringify(nextFields),
    timeSpentMs: input.timeSpentMs ?? null,
    reviewedAt: now.getTime(),
  });

  if (flashcard.siblingGroup) {
    await burySiblingCards({
      siblingGroup: flashcard.siblingGroup,
      currentCardId: flashcard.id,
      until: now.getTime() + 24 * 60 * 60 * 1000,
    });
  }

  await refreshLeechFlags(flashcard.id, result.card.lapses);

  return {
    flashcardId: flashcard.id,
    dueAt: result.card.due.getTime(),
    state: stateToString(result.card.state),
    predictions: engine.getPredictions(result.card, now),
    remainingDue: await countDueFlashcards(),
  };
}

export async function undoLastManagedReview(flashcardId: string) {
  const [history, latestReview] = await Promise.all([
    getLatestReviewHistory(flashcardId),
    getLatestReviewRecord(flashcardId),
  ]);

  if (!history) {
    return null;
  }

  const previous = JSON.parse(history.previousState) as Record<string, unknown>;
  await updateFlashcardById(flashcardId, {
    fsrsDue: typeof previous.fsrsDue === "number" ? previous.fsrsDue : null,
    fsrsState: typeof previous.fsrsState === "string" ? previous.fsrsState : "new",
    fsrsStability: typeof previous.fsrsStability === "number" ? previous.fsrsStability : 0,
    fsrsDifficulty: typeof previous.fsrsDifficulty === "number" ? previous.fsrsDifficulty : 0,
    fsrsElapsedDays: typeof previous.fsrsElapsedDays === "number" ? previous.fsrsElapsedDays : 0,
    fsrsScheduledDays: typeof previous.fsrsScheduledDays === "number" ? previous.fsrsScheduledDays : 0,
    fsrsReps: typeof previous.fsrsReps === "number" ? previous.fsrsReps : 0,
    fsrsLapses: typeof previous.fsrsLapses === "number" ? previous.fsrsLapses : 0,
    fsrsLastReview: typeof previous.fsrsLastReview === "number" ? previous.fsrsLastReview : null,
    learningStep: typeof previous.learningStep === "number" ? previous.learningStep : 0,
    intervalDays: typeof previous.intervalDays === "number" ? previous.intervalDays : 0,
    easeFactor: typeof previous.easeFactor === "number" ? previous.easeFactor : 2.5,
  });

  await markReviewHistoryUndone(history.id);

  if (latestReview) {
    await deleteReviewRecord(latestReview.id);
  }

  return {
    historyId: history.id,
    remainingDue: await countDueFlashcards(),
  };
}
